### ISSUE TITLE
IndexError in vlmap_builder.py

### ISSUE THREAD

**Issue by Star-down** [avlmaps/AVLMaps#4]
@Tom-Huang Hello,I'm sorry for taking up your time. I encountered some errors.
![图片](https://github.com/avlmaps/AVLMaps/assets/70835342/0e299bce-c44c-44ef-920d-b107b1a0abec)
When I was working on "Create a AVLMap with the Generated Dataset" task, I encountered such an error in the vlmap_builder.py file. Is this error expected? Thank you very much!

**Comment by Tom-Huang** [comment]
Hi @Star-down, thank you for your interest in our project. I just noticed a bug in the code and fixed it. In short, line 157-158 in your screenshot missed an assignment operation. These two lines actually need to call `self._reserve_map_space` to allocate more space for `grid_feat`, `grid_pos`, `weight`, and `grid_rgb`.

**Comment by Star-down** [comment]
Thank you very much for your assistance, I have started the process of creating AVLMap.
